
"use strict";
const DATA=window.GHOSTLIGHT_CODEX;
const ROOT=document.querySelector("#main");
let currentHeading=null;
const KEY="ghostlight-codex-progress-v2";
const ANSWERS_KEY="ghostlight-codex-reflections-v2";
const CONTACT="wynter1990"; // User-approved public reward for every finisher.
const FIT=[
 {label:"Relationship direction",text:"I want a committed relationship, monogamous by default. I may consider polyfidelity in the right circumstances, but I do not require it."},
 {label:"Values and disagreement",text:"I am liberal-leaning and care about equal rights. I can make room for good-faith disagreement; ideological rigidity is a mismatch. Lawful gun ownership alone is not a dealbreaker for me."},
 {label:"Faith and partnership",text:"Cultural or Eastern Christian background and private belief are fine. I do not want a church-centered, Jesus-centered, or conversion-focused partnership."},
 {label:"Autonomy and consent",text:"When a partner says no or asks for space, I respect it without pressure, punishment, sulking, or attempts to control their choice."}
];
const PROMPTS=[
 {title:"Before ordinary-life chapters",text:"The next chapters discuss health, sleep, access needs, and food. You do not need to provide medical or caregiving information about yourself to continue."},
 {title:"Before bonds and home",text:"The next chapters include family and relationship context. Other people are described from Wynter's perspective; respect their boundaries and privacy. Their details are included only as needed to understand Wynter's own story."},
 {title:"Before projects and skills",text:"The next chapters describe work and abilities. No puzzle skill, income, speed, or amount of free time is used as a measure of partner worth."},
 {title:"Before worldview and expression",text:"The next chapters include values, spirituality, aesthetics, and social context. You can disagree respectfully or leave; there is no preferred script."},
 {title:"Before deeper context",text:"The next non-graphic section includes Wynter's account of childhood sexual abuse, past suicidal crisis, sexual coercion and assault, physical violence, psychiatric hospitalization, and police and custody conflict. Read only if you choose; you can leave at any time. You never need to disclose trauma or intimate details of your own."},
 {title:"Before the reference record",text:"The last chapters include detailed reference material and how the Codex changed over time. This content is personal and may be copied from the static site."}
];
const REFLECTIONS=[
 {title:"Space and disappointment",prompt:"Someone you’re dating says, ‘I’m overloaded tonight. I need space, and I’ll reach out tomorrow.’ What would you do, including how you’d handle your own disappointment?"},
 {title:"Repair after a hurtful joke",prompt:"You make a joke; the other person says it hurt and asks you not to joke about that again. What would you say or do first, and how would you handle it if they are not ready to reassure you?"},
 {title:"Keeping a confidence",prompt:"Someone tells you something personal in confidence; later a friend asks what is going on. What would you protect, and what would make sharing appropriate?"},
 {title:"A lower-pressure week",prompt:"A date asks for a lower-pressure week during a busy stretch. What agreement could work for both of you, and what would you do if plans change or effort stops feeling mutual?"}
];
const SIDE_PUZZLES={
 1:{title:"Doubling signal",prompt:"2 · 4 · 8 · 16 · ?",options:["20","24","32"],answer:"32",hint:"Each number is twice the one before it."},
 3:{title:"Skip-letter signal",prompt:"A · C · E · G · ?",options:["H","I","J"],answer:"I",hint:"The sequence advances two letters at a time."},
 5:{title:"Growing signal",prompt:"1 · 1 · 2 · 3 · 5 · ?",options:["7","8","9"],answer:"8",hint:"Each new number is the sum of the previous two."}
};
function readAnswers(){try{return JSON.parse(sessionStorage.getItem(ANSWERS_KEY)||"{}")}catch{return {}}}
function writeAnswers(value){try{sessionStorage.setItem(ANSWERS_KEY,JSON.stringify(value))}catch{}}
function clearJourney(){sessionStorage.removeItem(KEY);sessionStorage.removeItem(ANSWERS_KEY);sessionStorage.removeItem("ghostlight-codex-progress-v1");sessionStorage.removeItem("ghostlight-codex-reflections-v1")}
function read(){try{const n=Number(sessionStorage.getItem(KEY));return Number.isInteger(n)&&n>=0?n:0}catch{return 0}}
function save(n){try{sessionStorage.setItem(KEY,String(n))}catch{}}
function node(tag,attrs={},text=""){const e=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==="class")e.className=v;else if(k.startsWith("aria-"))e.setAttribute(k,v);else e.setAttribute(k,v)}if(text)e.textContent=text;return e}
function shell(step,label,title,lead){ROOT.replaceChildren();const p=node("div",{class:"progress-wrap"});const lab=node("label",{for:"path-progress"},`Journey progress · ${step} of 7 acts`);const bar=node("progress",{id:"path-progress",max:"7",value:String(Math.min(step,7))});p.append(lab,bar);currentHeading=node("h1",{tabindex:"-1"},title);ROOT.append(p,node("p",{class:"step-label"},label),currentHeading,node("p",{class:"lead"},lead))}
function button(label,fn,secondary=false){const b=node("button",{type:"button",class:secondary?"secondary":"primary"},label);b.addEventListener("click",fn);return b}
function renderIntro(){shell(0,"OPENING TRANSMISSION","A longer signal, in seven acts","Ghostlight is a paced introduction to Wynter through the complete White Wynter Codex 2026.");const box=node("section",{class:"panel"});box.append(node("h2",{},"What you will encounter"));const list=node("ul",{class:"topic-list"});for(const a of DATA.acts)list.append(node("li",{},`${a.title}: ${a.focus}`));box.append(list);ROOT.append(box);const privacy=node("section",{class:"notice"});privacy.append(node("h2",{},"Your choice and the limits of this site"),node("p",{},"Plan for about 90 minutes to read the full journey; it may take longer if you pause or write optional reflections."),node("p",{},"The fit check covers relationship direction, values, faith, and respect for autonomy. These are Wynter's stated preferences and your self-selection, not a character test or a verified claim."),node("p",{},"This experience includes personal material, including health, family, history, and intimacy topics. Wynter's Codex also includes her perspective on other people in her life; please respect their privacy and do not use those details to identify or contact them. You can stop at any point. Four optional reflection checkpoints ask how you might handle ordinary relationship situations; they are not scored and have no magic answers. Three optional pattern side puzzles are just for curiosity: no timer, score, or effect on chapter access."),node("p",{},"Your fit-gate choices and any written reflections stay in this browser tab's session storage and are not submitted. Session restore may keep them after closing the tab; use Clear journey data to remove them. At the end, you can review, edit, copy, or clear a self-authored packet. Do not include another person's private story. Puzzle choices are not recorded."),node("p",{},"The chapter files are included in a static site sent to your browser. Gates pace the story; they do not protect unreached chapters. Anyone can inspect or share the files before unlocking them. The web host may receive ordinary connection data when you load the site."),node("p",{},"For adults 18 and older. Completing the journey reveals Wynter's public Discord handle to every finisher. Completion does not promise a reply, date, or meeting."));ROOT.append(privacy,button("Begin with the fit check",()=>{clearJourney();save(1);render()}),button("Leave the signal",()=>{clearJourney();renderExit()},true))}
function renderFit(){shell(0,"THE FIRST GATE","Start with what has to fit","These are Wynter's stated dating constraints. This is transparent self-selection, not a personality test. Choose “fits” only if you mean it.");const form=node("form",{class:"fit-form","aria-describedby":"fit-error"});FIT.forEach((item,index)=>{const fs=node("fieldset"),legend=node("legend",{},item.label);fs.append(legend,node("p",{},item.text));[["fit","This fits what I want."],["uncertain","I am unsure or this is a mismatch."]].forEach(([value,label])=>{const l=node("label",{class:"choice"}),i=node("input",{type:"radio",name:`fit-${index}`,value,required:"required"});l.append(i,document.createTextNode(label));fs.append(l)});form.append(fs)});const ack=node("label",{class:"check-row"}),check=node("input",{type:"checkbox",required:"required"});ack.append(check,document.createTextNode("I understand this is only my own self-selection; no one is scoring or verifying my answers."));form.append(ack);const error=node("p",{class:"validation-error",id:"fit-error",role:"alert","aria-live":"assertive",tabindex:"-1"});form.append(error);const go=button("Continue",()=>{if(!form.checkValidity()){error.textContent="Please answer each of the four fit statements and check the acknowledgment before continuing.";error.focus();return}error.textContent="";const choices=[...form.querySelectorAll('input[type="radio"]:checked')],yes=choices.every(x=>x.value==="fit");if(yes){const answers=readAnswers();for(const choice of choices)answers[choice.name]=choice.value;writeAnswers(answers);save(2);render()}else renderExit()},false);form.append(go);ROOT.append(form,button("Leave the signal",()=>renderExit(),true))}
function renderExit(){clearJourney();shell(0,"SIGNAL CLOSED · NO JUDGMENT","The signal ends here","A mismatch, uncertainty, or choice to stop is enough. There is nothing to prove or explain.");ROOT.append(node("section",{class:"notice"},"This gate reflects only Wynter's stated preferences. It cannot judge anyone's character or predict a relationship. Any reflections entered in this journey have been cleared from this tab."),button("Return to the opening",()=>{clearJourney();render()}));currentHeading.focus()}
function normalizeHeading(value){return value.trim().replace(/\s+/g," ").toLocaleLowerCase()}
function renderSourceText(ch){const root=node("div",{class:"source-text"});const headings=new Set((ch.subheadings||[]).map(normalizeHeading));const primary=ch.number>0?normalizeHeading(`${ch.number}. ${ch.title}`):"";if(primary)headings.add(primary);const lines=ch.text.split(/\r?\n/);let paragraph=[];let list=null,canContinueList=false;const flushParagraph=()=>{if(paragraph.length){root.append(node("p",{},paragraph.join(" ")));paragraph=[]}};for(let i=0;i<lines.length;){const raw=lines[i],line=raw.trim();if(!line){flushParagraph();canContinueList=false;i++;continue}let headingText=null,consumed=1;const joined=i+1<lines.length?`${line} ${lines[i+1].trim()}`:"";if(headings.has(normalizeHeading(line)))headingText=line;else if(joined&&headings.has(normalizeHeading(joined))){headingText=joined;consumed=2}if(headingText){flushParagraph();list=null;canContinueList=false;const title=normalizeHeading(headingText)===primary;root.append(node(title?"h2":"h3",{},headingText));i+=consumed;continue}const bullet=line.match(/^(?:[-•])\s+(.*)$/);if(bullet){flushParagraph();if(!list){list=node("ul",{});root.append(list)}list.append(node("li",{},bullet[1]));canContinueList=true;i++;continue}if(list&&canContinueList&&/^\s{2,}\S/.test(raw)&&list.lastElementChild){list.lastElementChild.append(document.createTextNode(` ${line}`));i++;continue}list=null;canContinueList=false;paragraph.push(line);i++}flushParagraph();return root}
function renderSidePuzzle(puzzle){const box=node("section",{class:"panel side-puzzle","aria-labelledby":"side-puzzle-title"});box.append(node("h2",{id:"side-puzzle-title"},`Optional signal puzzle · ${puzzle.title}`),node("p",{},puzzle.prompt),node("p",{},"Just for curiosity. This has no score and never changes your route. Skip, ask for a hint, or reveal the answer whenever you like."));const group=node("fieldset",{class:"puzzle-choices"}),legend=node("legend",{},"Choose a pattern continuation");group.append(legend);puzzle.options.forEach((value,index)=>{const label=node("label",{class:"choice"}),radio=node("input",{type:"radio",name:"side-puzzle",value});label.append(radio,document.createTextNode(value));group.append(label)});const status=node("p",{class:"status","aria-live":"polite"});const actions=node("div",{class:"button-row"});actions.append(button("Check pattern",()=>{const chosen=group.querySelector?group.querySelector('input[name="side-puzzle"]:checked'):group.children.map(x=>x.children[0]).find(x=>x.checked);if(!chosen){status.textContent="Choose an option if you want to try, or skip this puzzle.";return}status.textContent=chosen.value===puzzle.answer?"Pattern spotted. The journey continues exactly the same either way.":"Not this pattern. Nothing is lost; try again, use a hint, reveal the answer, or skip."}),button("Show hint",()=>{status.textContent=`Hint: ${puzzle.hint}`},true),button("Reveal answer",()=>{status.textContent=`One pattern answer is ${puzzle.answer}. This changes no progress or reward.`},true),button("Skip puzzle",()=>{status.textContent="Puzzle skipped. Your chapters and progress are unchanged."},true));box.append(group,status,actions);return box}
function renderAct(actIndex){const act=DATA.acts[actIndex];shell(actIndex+1,`ACT ${String(actIndex+1).padStart(2,"0")}`,act.title,act.focus);const puzzle=SIDE_PUZZLES[actIndex];if(puzzle)ROOT.append(renderSidePuzzle(puzzle));const list=node("section",{class:"chapter-list"});act.chapters.forEach(n=>{const ch=DATA.chapters.find(x=>x.number===n);if(!ch)return;const details=node("details",{class:"chapter"});const summary=node("summary",{},`Earned chapter ${n===0?"·":n+" ·"} ${ch.title}`);const body=node("div",{class:"chapter-body"});body.append(node("p",{class:"source-pages"},`From the September 12, 2026 consolidated Codex · source page${ch.source_pages.length===1?"":"s"} ${ch.source_pages.join(", ")}`));body.append(renderSourceText(ch));details.append(summary,body);list.append(details)});ROOT.append(list);const row=node("div",{class:"button-row"});row.append(button(actIndex===DATA.acts.length-1?"Complete the journey":"Continue",()=>{save(read()+1);render()}));if(actIndex>0)row.append(button("Previous act",()=>{save(read()-1);render()},true));row.append(button("Leave the signal",()=>renderExit(),true));ROOT.append(row)}
function renderGate(gateIndex){const prompt=PROMPTS[gateIndex];shell(gateIndex+1,`THE NEXT GATE · ${String(gateIndex+1).padStart(2,"0")}`,prompt.title,prompt.text);const box=node("section",{class:"panel gate"});box.append(node("p",{},"Take a moment with the topic preview. Continue only if you want to read the next chapters."));let area=null;if(gateIndex<REFLECTIONS.length){const item=REFLECTIONS[gateIndex],fs=node("fieldset",{class:"reflection-field"}),legend=node("legend",{},`Optional reflection ${gateIndex+1} · ${item.title}`),label=node("label",{for:"reflection-answer"},"Your response");area=node("textarea",{id:"reflection-answer",rows:"6",maxlength:"1200","aria-describedby":"reflection-help reflection-status"});area.value=readAnswers()[String(gateIndex)]||"";const help=node("p",{id:"reflection-help"},"This is not scored and has no ideal phrase. Answer from your own reasoning; do not include someone else’s private information. You may continue without writing."),status=node("p",{id:"reflection-status",class:"status","aria-live":"polite"},"Optional · up to 1,200 characters");fs.append(legend,node("p",{},item.prompt),label,area,help,status);box.append(fs)}const ack=node("label",{class:"check-row"}),check=node("input",{type:"checkbox"}),ackStatus=node("p",{class:"status",role:"status","aria-live":"polite"});ack.append(check,document.createTextNode("I choose to continue."));check.addEventListener("change",()=>{if(check.checked)ackStatus.textContent=""});box.append(ack,ackStatus);const row=node("div",{class:"button-row"});row.append(button("Open the next act",()=>{if(!check.checked){ackStatus.textContent="Check the box if you want to continue, or choose Leave the signal.";check.focus();return}if(area){const value=area.value.trim(),answers=readAnswers();if(value)answers[String(gateIndex)]=value;else delete answers[String(gateIndex)];writeAnswers(answers)}save(read()+1);render()}));row.append(button("Previous act",()=>{save(read()-1);render()},true));row.append(button("Leave the signal",()=>renderExit(),true));box.append(row);ROOT.append(box)}
function renderFinish(){shell(7,"FINAL SIGNAL","You choose what happens next","You reached the final chapter. Nothing has been sent. Your response packet is optional and self-authored.");const box=node("section",{class:"notice"});box.append(node("h2",{},"The final reward"),node("p",{},"If you would like to continue, you can contact Wynter on Discord:"),node("p",{class:"contact"},CONTACT),node("p",{},"This handle is intentionally public to every finisher and can be copied or shared. Reaching this page does not promise a reply, a date, or a relationship."));const packet=node("section",{class:"panel"});packet.append(node("h2",{},"Your optional response packet"),node("p",{},"Review or edit this packet before choosing whether to share it. Copying does not send anything. These are self-reports, not validated evidence of character or compatibility."));const answers=readAnswers();const packetText=["My optional Ghostlight reflection packet",...FIT.map((x,i)=>`${x.label}: ${answers[`fit-${i}`]||"not recorded"}`),...REFLECTIONS.map((x,i)=>`${x.title}: ${answers[String(i)]||"(no response)"}`)].join("\n\n");const area=node("textarea",{id:"packet",rows:"14","aria-label":"Editable reflection packet"});area.value=packetText;const status=node("p",{class:"status","aria-live":"polite"});const actions=node("div",{class:"button-row"});actions.append(button("Copy packet",async()=>{try{await navigator.clipboard.writeText(area.value);status.textContent="Copied to clipboard. Nothing was sent."}catch{area.focus();area.select();status.textContent="Clipboard access was unavailable. The packet is selected; copy it with your browser's copy command."}}),button("Clear packet answers",()=>{sessionStorage.removeItem(ANSWERS_KEY);render()} ,true));packet.append(area,status,actions);ROOT.append(box,packet,button("Previous act",()=>{save(read()-1);render()},true),button("Clear journey data",()=>{clearJourney();render()},true))}
function render(){const s=read();if(s<=0)renderIntro();else if(s===1)renderFit();else{let cursor=2,shown=false;for(let i=0;i<DATA.acts.length;i++){if(s===cursor){renderAct(i);shown=true;break}cursor++;if(i<DATA.acts.length-1){if(s===cursor){renderGate(i);shown=true;break}cursor++}}if(!shown)renderFinish()}if(currentHeading)currentHeading.focus()}
render();

